### ISSUE TITLE
请问下，如何修复的CUE4parse的model导出呢？

### ISSUE THREAD

**Issue by zdone** [developer-ken/OpenDanmaki#3]
已经找到，感谢。本内容已删除。

**Comment by developer-ken** [comment]
交叉引用：https://github.com/FabianFG/CUE4Parse/issues/140

[FModel](https://github.com/4sval/FModel)设置里有鸣潮支持，可以参考。

**Comment by zdone** [comment]
> 交叉引用：[FabianFG/CUE4Parse#140](https://github.com/FabianFG/CUE4Parse/issues/140)
> 
> [FModel](https://github.com/4sval/FModel)设置里有鸣潮支持，可以参考。

找到了；谢谢。
